In [29]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
from sklearn.preprocessing import label_binarize
from sklearn.model_selection import train_test_split
from sklearn.tree import DecisionTreeClassifier
from sklearn.metrics import auc,roc_curve,accuracy_score,precision_score,recall_score,confusion_matrix,precision_recall_curve,roc_auc_score

In [36]:
import pickle

In [3]:
df = pd.read_csv("winequality-red.csv")

In [4]:
df.shape

(1599, 12)

In [5]:
df.head()

fixed acidity  volatile acidity  citric acid  residual sugar  chlorides  \
0            7.4              0.70         0.00             1.9      0.076   
1            7.8              0.88         0.00             2.6      0.098   
2            7.8              0.76         0.04             2.3      0.092   
3           11.2              0.28         0.56             1.9      0.075   
4            7.4              0.70         0.00             1.9      0.076   

   free sulfur dioxide  total sulfur dioxide  density    pH  sulphates  \
0                 11.0                  34.0   0.9978  3.51       0.56   
1                 25.0                  67.0   0.9968  3.20       0.68   
2                 15.0                  54.0   0.9970  3.26       0.65   
3                 17.0                  60.0   0.9980  3.16       0.58   
4                 11.0                  34.0   0.9978  3.51       0.56   

   alcohol  quality  
0      9.4        5  
1      9.8        5  
2      9.8        5  
3      9.8        6  
4      9.4        5

In [41]:
df.columns

Index(['fixed acidity', 'volatile acidity', 'citric acid', 'residual sugar',
       'chlorides', 'free sulfur dioxide', 'total sulfur dioxide', 'density',
       'pH', 'sulphates', 'alcohol', 'quality'],
      dtype='object')

In [6]:
df['quality'].unique()

array([5, 6, 7, 4, 8, 3])

In [8]:
X = df.drop(['quality'],axis=1)
y = df['quality']

In [9]:
Xtrain,Xtest,ytrain,ytest = train_test_split(X,y,test_size=0.2,random_state=34)
print(Xtrain.shape,Xtest.shape,ytrain.shape,ytest.shape)

(1279, 11) (320, 11) (1279,) (320,)


In [10]:
clf = DecisionTreeClassifier()
clf.fit(Xtrain,ytrain)

DecisionTreeClassifier()

In [11]:
ypred = clf.predict(Xtest)

In [20]:
# Metrics
accuracy = accuracy_score(ytest,ypred)
recall = recall_score(ytest,ypred,average='macro')
precision = precision_score(ytest,ypred,average='micro')
con_mat = confusion_matrix(ytest,ypred)

In [21]:
print("Accuracy : ",accuracy)
print("Recall : ",recall)
print("Precision : ",precision)
print("con_mat : ",con_mat)

Accuracy :  0.59375
Recall :  0.2963137051322743
Precision :  0.59375
con_mat :  [[ 0  0  4  1  0  0]
 [ 0  0  5  3  0  0]
 [ 0  1 89 35  4  0]
 [ 1  1 30 80 18  1]
 [ 0  0  3 19 21  1]
 [ 0  0  0  1  2  0]]


In [35]:
# predicting for individual values
single_prediction  = clf.predict([[7.5, 0.65, 0.12, 2.1, 0.085, 12.0, 45.0, 0.9975, 3.35, 0.60, 10.2]])
single_prediction

/Users/ravikantkumar/anaconda3/envs/test_env/lib/python3.12/site-packages/sklearn/base.py:493: UserWarning: X does not have valid feature names, but DecisionTreeClassifier was fitted with feature names
  warnings.warn(


array([5])

In [40]:
# Creating pickle
with open('model.pkl','wb') as file:
    pickle.dump(clf,file)